dist: xenial
sudo: false

language: php
php:
  - 7.2

env:
  - APP_ENV=testing

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
