dist: xenial
sudo: required

language: php
php:
  - 7.2

notifications:
  email: false

env:
  - APP_ENV=testing


## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer install ${COMPOSER_FLAGS} --no-interaction --prefer-dist --no-suggest

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
