on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project # This would actually build your project, using zip for an example artifact
        id: build_project
        run: |
          FILE="gamify-laravel-${{ github.ref }}"
          COMPOSER_ARCHIVE_OPTIONS="--file=$FILE"
          composer build
          echo '::set-env name=FILE::$FILE'
      - name: Print var
        run: |
          echo "1. $FILE"
          echo "2. ${{ FILE }}"
          echo "3. ${{ steps.build_project.outputs.file }}"
          echo "4. ${{ steps.build_project.outputs.FILE }}"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset (zip)
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/gamify-laravel-${{ github.ref }}.zip
          asset_name: gamify-laravel-${{ github.ref }}.zip
          asset_content_type: application/zip
