name: Pint

on:
  pull_request:
    paths:
      - '**.php'

jobs:
  pint:
    name: pint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Pint
        uses: aglipanci/laravel-pint-action@0.1.0
        with:
          preset: laravel
